### ISSUE TITLE
PDF pagination (still?) broken

### ISSUE THREAD

**Issue by jgscudder** [ietf-tools/datatracker#4343] opened 2022-08-18 17:08 UTC
### Describe the issue

The page breaks on the PDF of draft-ietf-idr-bgp-ls-flex-algo-09 are a hot mess. This has been true of all the PDFized drafts I've looked at lately, but I was hoping it was only on older ones. Nope, this one is dated July 23, 2022.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by larseggert** [comment] 2022-08-18 17:17
This will hopefully be fixed by #4082

**Comment by rjsparks** [comment] 2022-08-18 23:20
Duplicate of #4331

**Comment by larseggert** [comment] 2022-12-12 17:05
@jgscudder could you recheck the current version?

**Comment by jgscudder** [comment] 2022-12-12 18:02
@larseggert it's less bad than it was, but the example I looked at, https://datatracker.ietf.org/doc/pdf/draft-ietf-idr-rfc7752bis-14 , still has wrong pagination. :-( In this case page 17 spills onto page 18, page 19 onto page 20, page 30 onto page 31, and so on.

I guess "hot mess" doesn't apply any more though :-) it's just extra pages that have nothing but a footer on them, now.

**Comment by larseggert** [comment] 2022-12-13 06:26
Ah! The CSS font for the 4th-level headings is too big. Will fix.

**Closed** 2022-12-13 16:10 UTC
Labels: bug, accepted
