### ISSUE TITLE
Character Rendering Weirdness

### ISSUE THREAD

**Issue by day** [ietf-tools/datatracker#7737] opened 2024-07-23 01:10 UTC
### Describe the issue

Just sitting in a session at 120 and noticed this. Not a big deal, but figured I'd drop it in here just in case it's an easy fix. Characters were not rendering properly...and then later, they were. So this issue was transient; possibly due a font not loading or...? I didn't really do much troubleshooting or thinking about this. I'm running Brave version 1.64.109 Chromium: 123.0.6312.58 (Official Build) (arm64).
<img width="559" alt="Screenshot 2024-07-22 at 5 51 19 PM" src="https://github.com/user-attachments/assets/79a049a8-7a49-4e5d-bf39-90c88910a96e">
<img width="1482" alt="Screenshot 2024-07-22 at 5 50 50 PM" src="https://github.com/user-attachments/assets/d70e35c7-b96a-401b-890e-99f366f387b5">
<img width="641" alt="Screenshot 2024-07-22 at 5 52 23 PM" src="https://github.com/user-attachments/assets/97122ef2-7624-422b-9b3c-183842a68895">

It wasn't page specific and showed up incorrectly in several views:
<img width="153" alt="Screenshot 2024-07-22 at 5 52 50 PM" src="https://github.com/user-attachments/assets/4f733d27-245a-4b6a-83eb-1855ea48608d">

...until it didn't and everything was normal again.
<img width="137" alt="Screenshot 2024-07-22 at 5 53 39 PM" src="https://github.com/user-attachments/assets/cd634bab-aa72-4567-bf22-d801e87ae9b2">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment] 2024-07-23 16:54
This is a duplicate of #7736 (and that is a repeat of something we saw at IETF-118). Closing in favor of that issue, but thank you for the report!

**Closed by jennifer-richards** 2024-07-23 16:54 UTC
Labels: bug
