### ISSUE TITLE
Internet-Draft and RFC statistics bug

### ISSUE THREAD

**Issue by xulu2024** [ietf-tools/datatracker#8247] opened 2024-11-21 07:19 UTC
### Describe the issue

i can't get the data from Internet-Draft and RFC statistics if i choose option document type with "RFC![Image](https://github.com/user-attachments/assets/72374b5a-df9c-45a3-96e7-fdb70093e260)
![Image](https://github.com/user-attachments/assets/0733c850-1984-45ac-96d0-e72b516ecd65)
s"
e.g https://datatracker.ietf.org/stats/document/author/country/?showaliases=1&type=rfc

### Code of Conduct

- [x] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment] 2024-11-21 16:12
I think this is a duplicate of https://github.com/ietf-tools/datatracker/issues/7742. Please follow that instead.

Feel free to reopen if I'm mistaken.

**Closed by jennifer-richards** 2024-11-21 16:12 UTC
Labels: bug
