### ISSUE TITLE
Add 'mastodon' to external resources

### ISSUE THREAD

**Issue by richsalz** [ietf-tools/datatracker#5083] opened 2023-02-03 15:06 UTC
### Description

You know, along with 'github' and the other tags.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by JayDaley** [comment] 2023-02-03 16:21
Duplicate of #5082

**Closed by JayDaley** 2023-02-03 16:21 UTC
Labels: enhancement
