### ISSUE TITLE
Searching for RFCs in dt-rfc seems broken

### ISSUE THREAD

**Issue by paulehoffman** [ietf-tools/datatracker#6672] opened 2023-11-20 23:14 UTC
### Describe the issue

When I type "8499" in the search box for the current Datatracker, I see both RFC 8499 and a draft that revises that RFC. In the dt-rfc instance, only the draft appears in the list. Entering "8450" in the dt-rfc search box doesn't find the RFC.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2023-11-20 23:36
Duplicate of #6665 I think (You are talking about the upper right search box, correct?)

**Comment by paulehoffman** [comment] 2023-11-21 00:44
Yes, that's probably a duplicate.

**Comment by paulehoffman** [comment] 2023-11-21 00:46
But, with the "8450" does appear correctly in the current Datatracker: 
<img width="217" alt="image" src="https://github.com/ietf-tools/datatracker/assets/638939/044332f5-7705-4c97-aa12-9a397f7c440d">

**Comment by rjsparks** [comment] 2023-11-22 18:46
Closing this - see #6665's resolution.

**Closed by rjsparks** 2023-11-22 18:46 UTC
Labels: bug
