### ISSUE TITLE
Status-change document creation reports that RFCs do not exist

### ISSUE THREAD

**Issue by jguichard1966** [ietf-tools/datatracker#5967] opened 2023-07-14 12:29 UTC
### Describe the issue

When trying to create a status-change document https://datatracker.ietf.org/doc/start-rfc-status-change/ the datatracker reports that the RFCs do not exist. 

![Screenshot (1)](https://github.com/ietf-tools/datatracker/assets/100449259/f1ae063a-7634-4892-8e2c-fcbb5ff5dc61)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2023-07-14 23:43
Duplicate of #5962. Fix is in PR #5963. Deployment will likely be after IETF 117.

**Closed by rjsparks** 2023-07-14 23:43 UTC
Labels: bug, duplicate
