### ISSUE TITLE
URL for proposing slides

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#4322] opened 2022-08-15 14:48 UTC
### Description

As a chair I often send (new) speakers the link to upload slides by email. However, I always have a hard time to find that link, as there is no "propose slides" button in the chairs' material view. Would also be nice to generally make it easier for speaker to find that link, e.g. by editing a button to the https://datatracker.ietf.org/meeting/materials page or even agenda page.

P.S.: the URL for proposing slides is also not easy to construct because it has the session id in the URL, e.g. https://datatracker.ietf.org/meeting/114/session/29667/propose_slides

So what I usually do as chair is to click on the upload slide button and then change "slides" to "proposed_slides" in the URL...

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2022-08-15 15:18
See also https://github.com/ietf-tools/datatracker/issues/3725

**Comment by rjsparks** [comment] 2022-09-09 21:34
Closing this as a duplicate of #3725.

For the P.S. There's not a good solution to the problem with guessing the URL (as there is the potential for multiple sessions per meeting, and ordering is not fixed over time).

**Closed by rjsparks** 2022-09-09 21:34 UTC
Labels: duplicate, enhancement

**Comment by mirjak** [comment] 2022-09-14 09:46
Just as a small comment, I don't think it actually important or maybe even confusing to assign slides to a specific session.

**Comment by rjsparks** [comment] 2022-09-14 14:47
It was very important to some chairs a previous meetings. In particular there was a meeting where a group made a strong division of what group of topics would be discussed at each session to make it clear for people managing conflicts which session was important for them to attend. They were adamant about the ability to associate slides with a single session, not just with the set of sessions at the meeting to support that effort.

**Comment by mirjak** [comment] 2022-09-14 16:08
I see. However, I think a more useful option would be that the participate can just upload slides and then the chairs can assign them to a specific session afterward. However, I assume that's more complicated to realise with the current system.
