### ISSUE TITLE
Finding author by email when parsing drafts at submission may not ignore case

### ISSUE THREAD

**Issue by rjsparks** [ietf-tools/datatracker#6057] opened 2023-07-27 19:38 UTC
Investigate whether an author that puts "MyName@SomeCompany.foo" will match a Person with an Email.address of "myname@somecompany.foo".

**Comment by rjsparks** [comment] 2023-07-28 15:34
likely a duplicate of #5929

**Comment by pselkirk** [comment] 2023-08-23 19:17
Closed as duplicate of #5929

**Closed by pselkirk** 2023-08-23 19:17 UTC
Labels: major, accepted, component: submit/
