### ISSUE TITLE
https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02 returns draft-ietf-secsh-filexfer-13.txt

### ISSUE THREAD

**Issue by ewxrjk** [ietf-tools/datatracker#5518] opened 2023-04-22 09:52 UTC
### Describe the issue

As title - If I ask for [draft-ietf-secsh-filexfer-02](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02) then the content I get back is draft-ietf-secsh-filexfer-13.txt. The same seems to be true for other revisions, though I didn't check all ten possibilities.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2023-04-23 15:44
duplicate of #4933. Please read the comments there.

**Closed by rjsparks** 2023-04-23 15:44 UTC
Labels: bug
