### ISSUE TITLE
sandbox: IAB meeting tap doesn't work 

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#6734] opened 2023-12-04 16:54 UTC
### Describe the issue

If I try to go on this page https://sandbox.ietf.org/group/iab/meetings/ I get "502 Bad Gateway".

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment] 2023-12-04 18:01
The sandbox there is out of date (but will be updated shortly).

**Comment by jennifer-richards** [comment] 2023-12-04 19:49
Sandbox is updated but this is persisting - will need to dig some more.

**Comment by rjsparks** [comment] 2023-12-04 20:00
The page takes a very long time to render, and is probably hitting an nginx timeout on sandbox.ietf.org (which is not a fast machine).

**Comment by rjsparks** [comment] 2023-12-04 20:00
In the meantime, if you want to explore (also on a machine that is not as fast as production, but it at least works), use https://dt-main.dev.ietf.org/group/iab/meetings/

**Comment by rjsparks** [comment] 2024-02-02 16:20
Closing this as OBE. The root cause is ietf.group.views.meetings being very inefficient with the database and that's being addressed as part of feat/iesgart

**Closed by rjsparks** 2024-02-02 16:20 UTC
Labels: bug
