### ISSUE TITLE
Missing older versions of OAuth 2.0

### ISSUE THREAD

**Issue by aaronpk** [ietf-tools/datatracker#5577] opened 2023-05-05 16:22 UTC
### Describe the issue

It used to be possible to find older versions of OAuth 2.0. Currently the datatracker page only links to versions 23 and above:

https://datatracker.ietf.org/doc/html/rfc6749

<img width="433" alt="image" src="https://user-images.githubusercontent.com/113001/236513051-7e2d72cb-2c2c-46f3-9118-3630731feab5.png">

Trying to construct the URL to an older version manually just shows the latest RFC6749, e.g.

https://datatracker.ietf.org/doc/html/draft-ietf-oauth-v2-22

The early drafts are also missing from the doc page navigation:

https://datatracker.ietf.org/doc/rfc6749/

<img width="863" alt="image" src="https://user-images.githubusercontent.com/113001/236513356-b3286e3c-c175-4843-b35d-5d8aedc91f75.png">

And clicking on the color bars for an old version just redirects back to rfc6749.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2023-05-05 19:25
Duplicate of https://github.com/ietf-tools/datatracker/issues/4933.

**Comment by rjsparks** [comment] 2023-06-15 19:03
(should have closed this as duplicate earlier - sorry for the noise - see #4933 and the PRs it mentions for the resolution).

**Closed by rjsparks** 2023-06-15 19:03 UTC
Labels: bug

**Comment by aaronpk** [comment] 2023-06-15 19:11
Sorry, the other ticket is locked so I can't comment on it. This does not appear to be entirely resolved yet. 

This page does now include the older versions in the side nav: https://datatracker.ietf.org/doc/html/rfc6749

<img width="416" alt="image" src="https://github.com/ietf-tools/datatracker/assets/113001/0af3fb28-6c46-4657-8c00-9ea17ed42785">

However, this page does not include the older versions in the nav, and the links to the old versions in the timeline are also broken: https://datatracker.ietf.org/doc/rfc6749/

<img width="1784" alt="image" src="https://github.com/ietf-tools/datatracker/assets/113001/973848ad-9ec4-430c-a4c6-c19a29640c1e">

**Comment by rjsparks** [comment] 2023-06-15 20:47
And as noted in the other ticket, those have _never_ been available on the main page.

The issue is that we don't have metadata for those versions and the main page shows the metadata.
To show something, we would either have to backfill DocHistory (which would involve making history up) or refactor the page completely so that we can say something like "we don't _know_ who the shepherd/responsible ad/etc was at this revision.

So for now it is "worked as designed". When we replace this page with a more reactive view (which is planned), we can go in with different requirements and make the experience for documents like this one less jarring.

**Comment by aaronpk** [comment] 2023-06-15 20:50
oh I see, fair enough. thanks!
