### ISSUE TITLE
Message : Meta-Data errors found! in a Internet-Draft submission

### ISSUE THREAD

**Issue by loco-philippe** [ietf-tools/datatracker#6172] opened 2023-08-20 22:00 UTC
### Describe the issue

Hello, 
I try to submit a Internet-Draft but the submission has been cancelled because some meta-data are not extracted correctly.
The message indicates a "Adjust meta-data" button below but i don't find any button below ??

File to be submitted : "draft-thomy-json-ntv.xml" <img width="716" alt="image" src="https://github.com/ietf-tools/datatracker/assets/92333742/4eea7c19-8f9b-4fcd-ba55-6dca223992cf">
Error Message:  <img width="1125" alt="Screenshot 2023-08-20" src="https://github.com/ietf-tools/datatracker/assets/92333742/8aa401d2-7051-4218-ba28-0ec885340d7a">

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by loco-philippe** [comment] 2023-08-21 15:33
thank you Robert for your quick response!

Sure enough, I'm sending the xml file to tools-help@ietf.org this morning.

About the filename, I tested several options (with the same "middle" section) but with different files (with the same negative result).

**Comment by jennifer-richards** [comment] 2023-08-22 15:00
The version of the file sent to tools-help had `version=""` at the end of the `<rfc...` element (rather than `version="0"` as in the screenshot above). As [noted on the issue we have for misleading submission status](https://github.com/ietf-tools/datatracker/issues/5696#issuecomment-1688294452), that seems to be the cause of the problem here. Changing that to `version="2"` allows the draft to be uploaded and accepted on the sandbox.

Closing this in favor of the existing issue and the one @rjsparks  created.

**Closed by jennifer-richards** 2023-08-22 15:00 UTC
Labels: bug

**Comment by loco-philippe** [comment] 2023-08-22 21:32
Thank you Jennifer,

You are right, the problem is solved with `version=2` !!

I will added a comment in #6183
