### ISSUE TITLE
Missing versions 0 to 12 of `draft-ietf-secsh-filexfer-xx`.

### ISSUE THREAD

**Issue by jfrech** [ietf-tools/datatracker#4946] opened 2023-01-04 08:53 UTC
### Describe the issue

All `.txt` file endpoints do still exist:
```sh
$ for n in $(seq 0 13); do url="$(printf 'https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-%02d.txt' $n)"; curl -fsSL -o/dev/null "$url" && echo "$url"; done
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-00.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-01.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-02.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-03.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-04.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-05.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-06.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-07.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-08.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-09.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-10.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-11.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-12.txt
https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-13.txt
```

However, e.&hairsp;g. [OpenSSH's specification](https://www.openssh.com/specs.html) links specifically to the last protocol version 3 draft, `draft-ietf-secsh-filexfer-02` via the endpoint https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02 which incorrectly shows an HTML representation of the final draft (the same is true for all fourteen drafts). The [timeline](https://datatracker.ietf.org/doc/draft-ietf-secsh-filexfer/) is also dysfunctional, refusing navigation.

Looking at the [Wayback Machine](https://web.archive.org/web/20221001071212/https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02), this regression seems to have taken place between 2022-10-01 and 2023-01-04.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2023-01-04 15:27
Duplicate of #4933.
(And the regression you are noting was most likely part of the shutdown of tools.ietf.org).

**Closed** 2023-01-04 15:27 UTC
Labels: bug, duplicate

**Comment by ikhtearalamshawonmollah54321** [comment] 2023-01-07 10:13
@jfrech #4957

**Comment by ikhtearalamshawonmollah54321** [comment] 2023-01-07 10:14
> ### Describe the issue
> All `.txt` file endpoints do still exist:
> 
> ```shell
> $ for n in $(seq 0 13); do url="$(printf 'https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-%02d.txt' $n)"; curl -fsSL -o/dev/null "$url" && echo "$url"; done
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-00.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-01.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-02.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-03.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-04.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-05.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-06.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-07.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-08.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-09.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-10.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-11.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-12.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-13.txt
> ```
> 
> However, e. g. [OpenSSH's specification](https://www.openssh.com/specs.html) links specifically to the last protocol version 3 draft, `draft-ietf-secsh-filexfer-02` via the endpoint https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02 which incorrectly shows an HTML representation of the final draft (the same is true for all fourteen drafts). The [timeline](https://datatracker.ietf.org/doc/draft-ietf-secsh-filexfer/) is also dysfunctional, refusing navigation.
> 
> Looking at the [Wayback Machine](https://web.archive.org/web/20221001071212/https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02), this regression seems to have taken place between 2022-10-01 and 2023-01-04.
> 
> ### Code of Conduct
> * [x]  I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

Duplicate of #

>

**Comment by ikhtearalamshawonmollah54321** [comment] 2023-01-07 10:56
> ### Describe the issue
> All `.txt` file endpoints do still exist:
> 
> ```shell
> $ for n in $(seq 0 13); do url="$(printf 'https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-%02d.txt' $n)"; curl -fsSL -o/dev/null "$url" && echo "$url"; done
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-00.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-01.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-02.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-03.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-04.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-05.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-06.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-07.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-08.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-09.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-10.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-11.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-12.txt
> https://www.ietf.org/archive/id/draft-ietf-secsh-filexfer-13.txt
> ```
> 
> However, e. g. [OpenSSH's specification](https://www.openssh.com/specs.html) links specifically to the last protocol version 3 draft, `draft-ietf-secsh-filexfer-02` via the endpoint https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02 which incorrectly shows an HTML representation of the final draft (the same is true for all fourteen drafts). The [timeline](https://datatracker.ietf.org/doc/draft-ietf-secsh-filexfer/) is also dysfunctional, refusing navigation.
> 
> Looking at the [Wayback Machine](https://web.archive.org/web/20221001071212/https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02), this regression seems to have taken place between 2022-10-01 and 2023-01-04.
> 
> ### Code of Conduct
> * [x]  I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)
