### ISSUE TITLE
Title bar search does not find RFCs (on feat/rfc branch)

### ISSUE THREAD

**Issue by jennifer-richards** [ietf-tools/datatracker#6665] opened 2023-11-20 01:08 UTC
### Describe the issue

Searching for an RFC by number using the document search in the top right of the title bar does not work on feat/rfc. E.g., typing "1818" returns "No results found". On the main branch, "RFC1818" is found.

A few numbers return documents, but this seems to be because it's finding drafts that mention RFC numbers in their names. As far as I can tell it's not finding RFC numbers directly at all.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2023-11-20 23:37
Root cause is the implementation of ajax_select2_search_docs - there's type tension to resolve.
The same root cause means the forms for entering new Downref registry entries are broken (that is, we need to correct all uses of SearchableDocument(s)Field).

**Comment by rjsparks** [comment] 2023-11-22 14:33
Fixed with #6679. Result is deployed at dt-rfc

**Closed by rjsparks** 2023-11-22 14:33 UTC
Labels: bug, major, component: doc/, feat/rfc
