### ISSUE TITLE
An ability to search people in the datatracker?

### ISSUE THREAD

**Issue by smyslov** [ietf-tools/datatracker#4843] opened 2022-12-07 07:07 UTC
### Description

The datatracker contains a directory of registered users, each with a public profile page. However, there seem to be no simple way to browse this directory or to search it for a particular member's public profile.
From time to time I run into the problem - I have to write a message to an IETF member, but I don't remember his/her e-mail. The way I solve this problem currently is sub-optimal - I search e-mail archives trying to find a message from this person (and I have to guess which area this person is active in). Another way is an attempt to find a draft/RFC via datatracker that this person authored. If I'm lucky and such a draft/RFC exists, then its metadata page contains a link to this person's public profile where his/her e-mails are listed. Both ways are time consuming and not reliable.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2022-12-07 21:34
Duplicate of #3011

**Comment by rjsparks** [comment] 2022-12-07 21:35
at

>  I search e-mail archives trying to find a message from this person (and I have to guess which area this person is active in).

Why do you need to guess the area? The mailarchive tool lets you search the _entire archive_...

**Closed by rjsparks** 2022-12-07 21:34 UTC
Labels: duplicate, enhancement

**Comment by smyslov** [comment] 2022-12-13 12:35
I usually search my local mail archives :-)
