### ISSUE TITLE
Additional Resources `tracker` defaults to link text "Issuer Tracker" instead of "Issue Tracker"  

### ISSUE THREAD

**Issue by dkg** [ietf-tools/datatracker#7002] opened 2024-01-30 20:01 UTC
### Describe the issue

For example, look at https://datatracker.ietf.org/doc/draft-ietf-openpgp-pqc/ -- the "Additional Resources" section says:

```
github_repo https://github.com/openpgp-pqc/draft-openpgp-pqc/
tracker https://github.com/openpgp-pqc/draft-openpgp-pqc/issues
```

but the visible text says [Issuer Tracker](https://github.com/openpgp-pqc/draft-openpgp-pqc/issues).  It should just be "Issue Tracker".  The tooltip text is likewise "Issuer" instead of "Issue".

This is a trivial issue.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2024-02-01 22:22
Aiming this at the upcoming codesprint as a good issue to bring a new contributor up to speed with. If it needs resolution earlier, say so and we'll get it fixed.

**Comment by dkg** [comment] 2024-02-02 18:56
definitely not urgent from my side ☺  I fully support using it as a way
to ease in new contributors.

**Comment by 253700** [comment] 2024-02-03 17:00
1. [
Duplicate of #](url)

**Comment by 253700** [comment] 2024-02-03 17:00
Ddd

**Comment by rjsparks** [comment] 2024-03-16 01:41
Fixed in production using the admin (this is an ietf.name.models.ExtResourceName object) - will show up in dev instances after the next dev db build.

**Closed by rjsparks** 2024-03-16 01:41 UTC
Labels: bug, trivial, accepted, component: doc/, component: group/, contrib-easy
