### ISSUE TITLE
Some links are not clickable in Safari

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#4960] opened 2023-01-09 11:47 UTC
### Describe the issue

I believe since the last update some of the links are not clickable correctly in Safari. 

E.g on this page: https://datatracker.ietf.org/doc/bofreq-thaler-bpf-ebpf/
when I mouse over the editor names or additional resources the mouse icon does not change into a hand and I cannot click on the link. Weirdly I can right click and then e.g. say "open in new tab". 

Also the mouse-over information often only appears briefly or in a wrong position. 

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2023-01-09 15:21
I can't reproduce this with Safari at `Version 16.0 (17614.1.25.9.10, 17614)`. What version of the OS and what version of Safari are you encountering this with?

**Comment by larseggert** [comment] 2023-01-10 05:28
Is this an IT-managed system?

**Comment by rjsparks** [comment] 2023-01-10 16:17
@mirjak sent me OS and Safari Versions unicast. I tried the page above using the same versions at browserstack and still cannot reproduce the issue.

**Comment by rjsparks** [comment] 2023-01-10 21:09
I checked that URL using browserstack at your versions and don't see the issue there. I'll close this. Reopen it if you find evidence that it's not local to your machine.

**Closed by rjsparks** 2023-01-10 21:09 UTC
Labels: bug
