### ISSUE TITLE
Invalid URLs for WG Additional Resources

### ISSUE THREAD

**Issue by smyslov** [ietf-tools/datatracker#3990] opened 2022-05-19 16:23 UTC
### Describe the issue

When clicking on any link for Additional resources on a WG "About" page, the resulting URL is constructed incorrectly - it is falsly prepended with "https://datatracker.ietf.org/wg/uta/about" prefix. For example, for UTA WG the URL for Zulip stream is:
https://datatracker.ietf.org/wg/uta/about/https%3A//zulip.ietf.org/%23narrow/stream/136-uta
which leads to 404, instead of https://zulip.ietf.org/#narrow/stream/136-uta
Note, that URLs themselves are configured correctly (on "Edit" page for Additional resources).

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2022-05-19 16:42
Duplicate of #3984

**Closed by rjsparks** 2022-05-19 16:42 UTC
Labels: bug, duplicate
