### ISSUE TITLE
HTML vs UTF-8 in messages from scheduling tool

### ISSUE THREAD

**Issue by cindymorgan** [ietf-tools/datatracker#7993] opened 2024-09-30 17:12 UTC
### Describe the issue

```
Mon Sep 30 00:57:30 2024 Windl, Ulrich <u.windl@ukr.de> 
From: 	"Windl, Ulrich" <u.windl@ukr.de>
To: 	"postmaster@ietf.org" <postmaster@ietf.org>
Date: 	Mon, 30 Sep 2024 07:57:18 +0000
Subject: 	FW: [EXT] [Ntp] ntp - New Meeting Session Request for IETF 121

Hi Postmaster,

the message below using HTML entities (&#x27;) in the name used "Content-Type: text/plain; charset="utf-8"" in the header, so the HTML entity is displayed literally. I guess it's not intended that way.

Kind regards,
Ulrich


-----Original Message-----
From: IETF Meeting Session Request Tool <session-request@ietf.org>
Sent: Wednesday, September 18, 2024 9:01 PM
To: session-request@ietf.org
Cc: ek.ietf@gmail.com; kodonog@pobox.com; ntp-chairs@ietf.org; ntp@ietf.org
Subject: [EXT] [Ntp] ntp - New Meeting Session Request for IETF 121
Importance: High



A new meeting session request has just been submitted by Karen
O&#x27;Donoghue, a Chair of the NTP Working Group.


---------------------------------------------------------
Working Group Name: Network Time Protocols
Area Name: Internet Area
Session Requester: Karen O&#x27;Donoghue


Number of Sessions: 1
Length of Session(s): 1.5 Hours
Number of Attendees: 30
Conflicts to Avoid:
Chair conflict: jose




Participants who must be present:

Resources Requested:

Special Requests:
Earlier in the week would be better if possible. There is a plan to have a Hackathon project, and if we can get an meeting session earlier in the week, we will likely have more in person attendees.

```

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2024-10-01 15:27
duplicate of #934

**Closed** 2024-10-09 19:49 UTC
Labels: bug
