### ISSUE TITLE
Scheduling interim meetings in series doesn't work

### ISSUE THREAD

**Issue by apelov** [ietf-tools/datatracker#6344] opened 2023-09-21 09:40 UTC
### Describe the issue

When requesting a series of virtual interim meetings, only the first session is scheduled, all others are ignored.

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by jennifer-richards** [comment] 2023-09-21 13:05
Thank you for the report. I believe this is a duplicate of #5595 - please reopen if I'm mistaken.

**Closed by jennifer-richards** 2023-09-21 13:05 UTC
Labels: bug
