### ISSUE TITLE
Link to PDF is missing (workshop material)

### ISSUE THREAD

**Issue by mirjak** [ietf-tools/datatracker#7017] opened 2024-02-05 11:59 UTC
### Describe the issue

This page doesn't have the link to the PDF: https://datatracker.ietf.org/doc/slides-biasws-imap-internet-monitoring-action-project-internet-censorship-report/

(Note the -00 version shows the link correctly)

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2024-02-05 18:26
duplicate of #7018?

**Comment by rjsparks** [comment] 2024-02-05 21:17
Please see the discussion in #7018 about root cause.

**Comment by rjsparks** [comment] 2024-02-09 15:49
Fixed with 12.5.0

**Closed by rjsparks** 2024-02-09 15:49 UTC
Labels: bug
