### ISSUE TITLE
Datatracker profile page for people

### ISSUE THREAD

**Issue by klensin** [ietf-tools/datatracker#4728] opened 2022-11-08 00:17 UTC
### Description

Hi.  If I look through the datatracker pages for specific documents, relevant groups, etc., I have no trouble finding links to the profiles for document authors, shepherds, group leaders, etc.  But, if I have a person's name and want to locate participating information, there appears to be no way, at least no obvious way, to find the profile page.   No information or links pointing to profiles in any of the pull-downs on the datatracker home page.    One might expect to find a pointer or search box at https://datatracker.ietf.org/person/, but nothing there (no such page, just, apparently, the top of a subtree).  

Could we get some obvious mechanism for searching the profile pages for individuals by their names?

thanks,
   john

### Code of Conduct

- [X] I agree to follow the [IETF's Code of Conduct](https://github.com/ietf-tools/.github/blob/main/CODE_OF_CONDUCT.md)

**Comment by rjsparks** [comment] 2022-11-09 10:08
duplicate of #3011

In the meantime, if you know a person's name or email address, you can type it into the url at
https://datatracker.ietf.org/person/Some Name

**Closed by rjsparks** 2022-11-09 10:08 UTC
Labels: enhancement
